name: Deploy ke Cloudflare Worker
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Bangun & Pasang
    permissions:
      contents: write
    steps:
      - name: Ambil kode dari repositori
        uses: actions/checkout@v4

      - name: Pasang Wrangler
        run: npm install -g wrangler

      - name: Masukkan rahasia & pasang
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | wrangler secret put GITHUB_TOKEN --name iptv1
          wrangler deploy --config wrangler.jsonc
        
